/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppSkillsRouteImport } from './routes/_app.skills'
import { Route as ApiChatRouteImport } from './routes/api.chat'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AppRResumeIdRouteImport } from './routes/_app.r.$resumeId'
import { Route as AppSkillsIndexRouteImport } from './routes/_app.skills.index'
import { Route as AppSkillsSkillIdRouteImport } from './routes/_app.skills.$skillId'
import { Route as AppRResumeIdIndexRouteImport } from './routes/_app.r.$resumeId.index'
import { Route as AppRResumeIdEditRouteImport } from './routes/_app.r.$resumeId.edit'
import { Route as AppRResumeIdExportRouteImport } from './routes/_app.r.$resumeId.export'
import { Route as AppRResumeIdHistoryRouteImport } from './routes/_app.r.$resumeId.history'
import { Route as AppRResumeIdInterviewRouteImport } from './routes/_app.r.$resumeId.interview'
import { Route as AppRResumeIdVersionsRouteImport } from './routes/_app.r.$resumeId.versions'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppSkillsRoute = AppSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => AppRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRResumeIdRoute = AppRResumeIdRouteImport.update({
  id: '/r/$resumeId',
  path: '/r/$resumeId',
  getParentRoute: () => AppRoute,
} as any)
const AppSkillsIndexRoute = AppSkillsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSkillsRoute,
} as any)
const AppSkillsSkillIdRoute = AppSkillsSkillIdRouteImport.update({
  id: '/$skillId',
  path: '/$skillId',
  getParentRoute: () => AppSkillsRoute,
} as any)
const AppRResumeIdIndexRoute = AppRResumeIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRResumeIdRoute,
} as any)
const AppRResumeIdEditRoute = AppRResumeIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AppRResumeIdRoute,
} as any)
const AppRResumeIdExportRoute = AppRResumeIdExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => AppRResumeIdRoute,
} as any)
const AppRResumeIdHistoryRoute = AppRResumeIdHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRResumeIdRoute,
} as any)
const AppRResumeIdInterviewRoute = AppRResumeIdInterviewRouteImport.update({
  id: '/interview',
  path: '/interview',
  getParentRoute: () => AppRResumeIdRoute,
} as any)
const AppRResumeIdVersionsRoute = AppRResumeIdVersionsRouteImport.update({
  id: '/versions',
  path: '/versions',
  getParentRoute: () => AppRResumeIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/dashboard': typeof AppDashboardRoute
  '/skills': typeof AppSkillsRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/r/$resumeId': typeof AppRResumeIdRouteWithChildren
  '/skills/$skillId': typeof AppSkillsSkillIdRoute
  '/skills/': typeof AppSkillsIndexRoute
  '/r/$resumeId/edit': typeof AppRResumeIdEditRoute
  '/r/$resumeId/export': typeof AppRResumeIdExportRoute
  '/r/$resumeId/history': typeof AppRResumeIdHistoryRoute
  '/r/$resumeId/interview': typeof AppRResumeIdInterviewRoute
  '/r/$resumeId/versions': typeof AppRResumeIdVersionsRoute
  '/r/$resumeId/': typeof AppRResumeIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/dashboard': typeof AppDashboardRoute
  '/api/chat': typeof ApiChatRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/skills/$skillId': typeof AppSkillsSkillIdRoute
  '/skills': typeof AppSkillsIndexRoute
  '/r/$resumeId/edit': typeof AppRResumeIdEditRoute
  '/r/$resumeId/export': typeof AppRResumeIdExportRoute
  '/r/$resumeId/history': typeof AppRResumeIdHistoryRoute
  '/r/$resumeId/interview': typeof AppRResumeIdInterviewRoute
  '/r/$resumeId/versions': typeof AppRResumeIdVersionsRoute
  '/r/$resumeId': typeof AppRResumeIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/skills': typeof AppSkillsRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_app/r/$resumeId': typeof AppRResumeIdRouteWithChildren
  '/_app/skills/$skillId': typeof AppSkillsSkillIdRoute
  '/_app/skills/': typeof AppSkillsIndexRoute
  '/_app/r/$resumeId/edit': typeof AppRResumeIdEditRoute
  '/_app/r/$resumeId/export': typeof AppRResumeIdExportRoute
  '/_app/r/$resumeId/history': typeof AppRResumeIdHistoryRoute
  '/_app/r/$resumeId/interview': typeof AppRResumeIdInterviewRoute
  '/_app/r/$resumeId/versions': typeof AppRResumeIdVersionsRoute
  '/_app/r/$resumeId/': typeof AppRResumeIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/logout'
    | '/dashboard'
    | '/skills'
    | '/api/chat'
    | '/auth/callback'
    | '/r/$resumeId'
    | '/skills/$skillId'
    | '/skills/'
    | '/r/$resumeId/edit'
    | '/r/$resumeId/export'
    | '/r/$resumeId/history'
    | '/r/$resumeId/interview'
    | '/r/$resumeId/versions'
    | '/r/$resumeId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/logout'
    | '/dashboard'
    | '/api/chat'
    | '/auth/callback'
    | '/skills/$skillId'
    | '/skills'
    | '/r/$resumeId/edit'
    | '/r/$resumeId/export'
    | '/r/$resumeId/history'
    | '/r/$resumeId/interview'
    | '/r/$resumeId/versions'
    | '/r/$resumeId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/logout'
    | '/_app/dashboard'
    | '/_app/skills'
    | '/api/chat'
    | '/auth/callback'
    | '/_app/r/$resumeId'
    | '/_app/skills/$skillId'
    | '/_app/skills/'
    | '/_app/r/$resumeId/edit'
    | '/_app/r/$resumeId/export'
    | '/_app/r/$resumeId/history'
    | '/_app/r/$resumeId/interview'
    | '/_app/r/$resumeId/versions'
    | '/_app/r/$resumeId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  ApiChatRoute: typeof ApiChatRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/skills': {
      id: '/_app/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof AppSkillsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/r/$resumeId': {
      id: '/_app/r/$resumeId'
      path: '/r/$resumeId'
      fullPath: '/r/$resumeId'
      preLoaderRoute: typeof AppRResumeIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/skills/': {
      id: '/_app/skills/'
      path: '/'
      fullPath: '/skills/'
      preLoaderRoute: typeof AppSkillsIndexRouteImport
      parentRoute: typeof AppSkillsRoute
    }
    '/_app/skills/$skillId': {
      id: '/_app/skills/$skillId'
      path: '/$skillId'
      fullPath: '/skills/$skillId'
      preLoaderRoute: typeof AppSkillsSkillIdRouteImport
      parentRoute: typeof AppSkillsRoute
    }
    '/_app/r/$resumeId/': {
      id: '/_app/r/$resumeId/'
      path: '/'
      fullPath: '/r/$resumeId/'
      preLoaderRoute: typeof AppRResumeIdIndexRouteImport
      parentRoute: typeof AppRResumeIdRoute
    }
    '/_app/r/$resumeId/edit': {
      id: '/_app/r/$resumeId/edit'
      path: '/edit'
      fullPath: '/r/$resumeId/edit'
      preLoaderRoute: typeof AppRResumeIdEditRouteImport
      parentRoute: typeof AppRResumeIdRoute
    }
    '/_app/r/$resumeId/export': {
      id: '/_app/r/$resumeId/export'
      path: '/export'
      fullPath: '/r/$resumeId/export'
      preLoaderRoute: typeof AppRResumeIdExportRouteImport
      parentRoute: typeof AppRResumeIdRoute
    }
    '/_app/r/$resumeId/history': {
      id: '/_app/r/$resumeId/history'
      path: '/history'
      fullPath: '/r/$resumeId/history'
      preLoaderRoute: typeof AppRResumeIdHistoryRouteImport
      parentRoute: typeof AppRResumeIdRoute
    }
    '/_app/r/$resumeId/interview': {
      id: '/_app/r/$resumeId/interview'
      path: '/interview'
      fullPath: '/r/$resumeId/interview'
      preLoaderRoute: typeof AppRResumeIdInterviewRouteImport
      parentRoute: typeof AppRResumeIdRoute
    }
    '/_app/r/$resumeId/versions': {
      id: '/_app/r/$resumeId/versions'
      path: '/versions'
      fullPath: '/r/$resumeId/versions'
      preLoaderRoute: typeof AppRResumeIdVersionsRouteImport
      parentRoute: typeof AppRResumeIdRoute
    }
  }
}

interface AppSkillsRouteChildren {
  AppSkillsSkillIdRoute: typeof AppSkillsSkillIdRoute
  AppSkillsIndexRoute: typeof AppSkillsIndexRoute
}

const AppSkillsRouteChildren: AppSkillsRouteChildren = {
  AppSkillsSkillIdRoute: AppSkillsSkillIdRoute,
  AppSkillsIndexRoute: AppSkillsIndexRoute,
}

const AppSkillsRouteWithChildren = AppSkillsRoute._addFileChildren(
  AppSkillsRouteChildren,
)

interface AppRResumeIdRouteChildren {
  AppRResumeIdEditRoute: typeof AppRResumeIdEditRoute
  AppRResumeIdExportRoute: typeof AppRResumeIdExportRoute
  AppRResumeIdHistoryRoute: typeof AppRResumeIdHistoryRoute
  AppRResumeIdInterviewRoute: typeof AppRResumeIdInterviewRoute
  AppRResumeIdVersionsRoute: typeof AppRResumeIdVersionsRoute
  AppRResumeIdIndexRoute: typeof AppRResumeIdIndexRoute
}

const AppRResumeIdRouteChildren: AppRResumeIdRouteChildren = {
  AppRResumeIdEditRoute: AppRResumeIdEditRoute,
  AppRResumeIdExportRoute: AppRResumeIdExportRoute,
  AppRResumeIdHistoryRoute: AppRResumeIdHistoryRoute,
  AppRResumeIdInterviewRoute: AppRResumeIdInterviewRoute,
  AppRResumeIdVersionsRoute: AppRResumeIdVersionsRoute,
  AppRResumeIdIndexRoute: AppRResumeIdIndexRoute,
}

const AppRResumeIdRouteWithChildren = AppRResumeIdRoute._addFileChildren(
  AppRResumeIdRouteChildren,
)

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppSkillsRoute: typeof AppSkillsRouteWithChildren
  AppRResumeIdRoute: typeof AppRResumeIdRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppSkillsRoute: AppSkillsRouteWithChildren,
  AppRResumeIdRoute: AppRResumeIdRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  ApiChatRoute: ApiChatRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
